### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by sara-n6** [sara-n6/HoMee#27]
■Webアプリの概要
このアプリは、タスク管理と褒め言葉を組み合わせたサービスです。 
達成したいタスクと、達成時に欲しい褒め言葉を登録し、褒められたい相手の画像も設定できます。 
タスクを達成すると、登録した相手の画像と褒め言葉がランダムに表示され、モチベーションを高めます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：15−20時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
https://github.com/users/sara-n6/projects/2/views/1

■MVPリリースまで
- [ ] rails new
- [ ] Renderにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] タスク登録
- [ ] タスク削除
- [ ] タスク編集
- [ ] タスク詳細
- [ ] 褒めてくれる相手登録
- [ ] 褒めてくれる相手削除
- [ ] 褒めてくれる相手編集
- [ ] 褒めてくれる相手一覧
- [ ] 褒め言葉登録
- [ ] タスク達成時ポップアップ

■MVP後
- [ ] リマインド機能
- [ ] ご褒美設定
- [ ] 褒めてくれる相手からのお手紙（メッセージ）機能（リマインドとともに）
- [ ] タスク達成レポート（週・月）
- [ ] レベル機能　あがると褒めてくれる相手の画像が変わる
- [ ] 褒めてくれる相手を自動で設定

■MVPレビュー依頼予定日
予定日：2025年 1月 12日

**Comment by Tsuchiya2** [comment]
<img width="895" alt="image" src="https://github.com/user-attachments/assets/4f157773-427d-495c-8f10-f3039b6335fc">

ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by sara-n6** [comment]
見落とししており申し訳ございません。
タスク達成ポップアップを2つにわけましたのでご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
